apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: echankio
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/echankio-harbor-project/app@sha256:7b074024e80ff33706aee133d11015bb0d5c9281b6636e5bd0090a8be2ba54a2
        ports:
        - containerPort: 5000
